# Generated by Django 5.0.4 on 2024-06-17 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='contents',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to='media'),
        ),
        migrations.CreateModel(
            name='ProductOrderingInformations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20)),
                ('value', models.CharField(max_length=4000)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tenant.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSpesifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20)),
                ('value', models.CharField(max_length=4000)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tenant.product')),
            ],
        ),
    ]
