# Generated by Django 5.0.4 on 2024-06-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_alter_product_contents_alter_product_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productorderinginformations',
            old_name='value',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='productorderinginformations',
            old_name='key',
            new_name='material',
        ),
        migrations.AddField(
            model_name='productorderinginformations',
            name='packaging',
            field=models.CharField(default=1, max_length=4000),
            preserve_default=False,
        ),
    ]
